name: Discord Webhook

on:
  push:
    branches: [ "main" ] # Default release branch
    paths-ignore:
      - '.github/**'
      - 'docs/**'

jobs:
  discord-titans:
    uses: Digitalroot-Valheim/.github/.github/workflows/discord.yml@main
    with:
      repo_name: ${{ github.event.repository.name }}
    secrets:
      webhook_url: ${{ secrets.VALHEIM_DISCORD_TITANS_WEBHOOK_URL }}

  discord-vl:
    uses: Digitalroot-Valheim/.github/.github/workflows/discord.yml@main
    with:
      repo_name: ${{ github.event.repository.name }}
    secrets:
      webhook_url: ${{ secrets.VALHEIM_DISCORD_VL_WEBHOOK_URL }}
