name: Publicize Assemblies

on:
  workflow_dispatch:

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:
  Install:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - name: Setup steamcmd
      uses: CyberAndrii/setup-steamcmd@v1.1.5
    - name: Update app
      run: |
        steamcmd +force_install_dir ./valheim +login anonymous +app_update 896660 validate +quit
    - name: ls
      run: | 
        pwd
        ls -lahoR
        ls -lahoR ~
