name: Publicize Assemblies

on:
  workflow_dispatch:

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:
  install:
    if: ${{ false }} # disable for now
    name: Install
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: write    
    steps:
    - name: Setup steamcmd
      uses: CyberAndrii/setup-steamcmd@v1.1.5
    - name: Update app
      run: |
        steamcmd +force_install_dir ~/.steam/steam/steamapps/common/Valheim +login anonymous +app_update 896660 validate +quit
    - name: List Files
      run: | 
        ls -dl ~/.steam/steam/steamapps/common/Valheim/valheim_server_Data/Managed/assembly_*.dll
    - name: Install Publicizer
      run: | 
        dotnet tool install -g BepInEx.AssemblyPublicizer.Cli
    - name: Publicize
      run: | 
        assembly-publicizer ~/.steam/steam/steamapps/common/Valheim/valheim_server_Data/Managed/assembly_googleanalytics.dll --strip -o ~/publicized_assemblies
        assembly-publicizer ~/.steam/steam/steamapps/common/Valheim/valheim_server_Data/Managed/assembly_guiutils.dll --strip -o ~/publicized_assemblies
        assembly-publicizer ~/.steam/steam/steamapps/common/Valheim/valheim_server_Data/Managed/assembly_lux.dll --strip -o ~/publicized_assemblies
        assembly-publicizer ~/.steam/steam/steamapps/common/Valheim/valheim_server_Data/Managed/assembly_postprocessing.dll --strip -o ~/publicized_assemblies
        assembly-publicizer ~/.steam/steam/steamapps/common/Valheim/valheim_server_Data/Managed/assembly_simplemeshcombine.dll --strip -o ~/publicized_assemblies
        assembly-publicizer ~/.steam/steam/steamapps/common/Valheim/valheim_server_Data/Managed/assembly_steamworks.dll --strip -o ~/publicized_assemblies
        assembly-publicizer ~/.steam/steam/steamapps/common/Valheim/valheim_server_Data/Managed/assembly_sunshafts.dll --strip -o ~/publicized_assemblies
        assembly-publicizer ~/.steam/steam/steamapps/common/Valheim/valheim_server_Data/Managed/assembly_utils.dll --strip -o ~/publicized_assemblies
        assembly-publicizer ~/.steam/steam/steamapps/common/Valheim/valheim_server_Data/Managed/assembly_valheim.dll --strip -o ~/publicized_assemblies
    - name: List Publicized Files
      run: | 
        pwd
        echo "ls -dlR ~/publicized_assemblies"
        ls -laR ~/publicized_assemblies
    - name: Checkout
      uses: actions/checkout@v3
    - name: Update Repo Files
      run: | 
        cp --verbose ~/publicized_assemblies/assembly_*.dll ./src/Digitalroot.Valheim.Common.References/lib/
    - name: Commit
      uses: stefanzweifel/git-auto-commit-action@v4


  call-workflow-nuget-release:
    needs: [install]
    uses: Digitalroot-Valheim/.github/.github/workflows/nuget.release.yml@main
    secrets:
      aws-access-key-id: ${{ secrets.NUGET_S3_REPO_KEY_ID }}
      aws-secret-access-key: ${{ secrets.NUGET_S3_REPO_KEY_SECRET }}
      nuget-org-key: ${{ secrets.NUGET_ORG_PAT }}
    with:
      sln-file-name: Digitalroot.Valheim.Common.References
      proj-file-name: Digitalroot.Valheim.Common.References
      #force-assembly-version: true
      nuget-gh-upload: true
      nuget-s3-upload: true
      nuget-org-upload: true
